services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev     
    container_name: reelix-bot-dev
    env_file:
      - .env
    volumes:
      - .:/app                       
      - /app/node_modules            
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: reelix-mongo-db-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: sashkayello_db_user
      MONGO_INITDB_ROOT_PASSWORD: 0ka8AJqrjXppnepP
    ports:
      - '27017:27017'
    volumes:
      - mongo-data-dev:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data-dev:

networks:
  app-network:
